name: ci
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy_and_archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-redirects mkdocs-git-revision-date-localized-plugin mkdocs-open-in-new-tab

      - name: Build MkDocs site
        run: mkdocs build

      - name: Archive the site directory
        run: |
          tar -czvf learnjapanese-moe-offline.tar.gz -C site .

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: learnjapanese-moe-offline-site
          path: learnjapanese-moe-offline.tar.gz
          retention-days: 7

      - name: Deploy to GitHub Pages (optional)
        run: mkdocs gh-deploy --force --clean
